<?php

namespace App\Models;

use App\Contracts\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Automatic AI feedback for a filed PIREP.
 *
 * Generated by App\Services\PirepFeedbackService and persisted through
 * phpvms:pireps-ai-feedback. It is advisory only: nothing in the PIREP
 * lifecycle reads it, so a failed analysis can never affect a flight.
 *
 * @property int         id
 * @property string      pirep_id
 * @property string      model
 * @property string|null verdict      Short headline, eg. "Aterrizaje suave pero largo"
 * @property int         severity     0 = correct, 1 = improvable, 2 = critical
 * @property array|null  good_points  Metrics that went well
 * @property array|null  errors       Concrete problems, each citing a value
 * @property string|null action       One measurable action for the next flight
 * @property string|null summary      Raw model response, kept for auditing
 * @property int|null    prompt_tokens
 * @property int|null    completion_tokens
 * @property int|null    total_tokens
 */
class PirepAiFeedback extends Model
{
    public const SEVERITY_OK = 0;

    public const SEVERITY_IMPROVABLE = 1;

    public const SEVERITY_CRITICAL = 2;

    public $table = 'pirep_ai_feedback';

    protected $fillable = [
        'pirep_id',
        'model',
        'verdict',
        'severity',
        'good_points',
        'errors',
        'action',
        'areas',
        'summary',
        'prompt_tokens',
        'completion_tokens',
        'total_tokens',
    ];

    protected $casts = [
        'severity'          => 'integer',
        'good_points'       => 'array',
        'errors'            => 'array',
        'areas'             => 'array',
        'prompt_tokens'     => 'integer',
        'completion_tokens' => 'integer',
        'total_tokens'      => 'integer',
    ];

    /**
     * Severity labels for the admin/staff views.
     */
    public static array $severity_labels = [
        self::SEVERITY_OK         => 'Correcto',
        self::SEVERITY_IMPROVABLE => 'Mejorable',
        self::SEVERITY_CRITICAL   => 'Crítico',
    ];

    public function pirep(): BelongsTo
    {
        return $this->belongsTo(Pirep::class, 'pirep_id');
    }

    public function severityLabel(): string
    {
        return self::$severity_labels[$this->severity] ?? 'Desconocido';
    }

    /**
     * Etiqueta de una valoracion por area, que usa la misma escala que
     * `severity` (0 correcto, 1 mejorable, 2 critico).
     */
    public function areaLabel(int $rating): string
    {
        return self::$severity_labels[$rating] ?? 'Sin valorar';
    }
}
